// Builds math.html from MATH.md.
//
// KaTeX runs here, at build time, with output:"mathml" — so the page ships as plain
// markup with no script, no stylesheet and no font to fetch, and stays inside the
// site's default-src 'none' CSP. Regenerate after editing MATH.md:
//
//   npm run build:math

const fs = require("fs");
const path = require("path");
const MarkdownIt = require("markdown-it");
const katex = require("@vscode/markdown-it-katex").default;

const root = path.join(__dirname, "..");
const SRC = path.join(root, "MATH.md");
const OUT = path.join(root, "math.html");

// The plugin owns the tricky part — telling `$x$` apart from an escaped `\$400` and
// keeping Markdown's inline rules off the TeX. Display math lands in
// <p class="katex-block">, inline math in <span class="katex">; both are styled below.
const md = new MarkdownIt({html: false, linkify: false, typographer: true})
  .use(katex, {output: "mathml", strict: false});

const body = md.render(fs.readFileSync(SRC, "utf8"));

const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- Generated by tools/mkmath.js from MATH.md — edit that, not this file. Nothing is
     fetched: the math is MathML the browser renders natively, and the CSS is inline. -->
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data: 'self'; form-action 'none'; base-uri 'none'">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="light dark">
<meta name="description" content="The amortization, PMI and cost-comparison math behind the Mortgage Offer Analyzer, derived from first principles.">
<link rel="icon" href="/icon-180.png">
<link rel="apple-touch-icon" sizes="180x180" href="/icon-180.png">
<title>The math behind the Mortgage Offer Analyzer</title>
<style>
  :root{
    color-scheme: light dark;
    --paper:#f4f5f2;
    --card:#ffffff;
    --ink:#161a1d;
    --slate:#5d6670;
    --line:#d9dcd6;
    --line-strong:#c2c7bf;
    --a:#0081a2;
    --mono:ui-monospace,"SF Mono",Menlo,Consolas,"Liberation Mono",monospace;
    --sans:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  }
  @media (prefers-color-scheme: dark){
    :root{
      --paper:#15181b; --card:#1e2226; --ink:#e8eaec; --slate:#a3acb5;
      --line:#31373d; --line-strong:#454d55; --a:#33a1bf;
    }
  }
  *{box-sizing:border-box}
  html,body{margin:0}
  html{-webkit-text-size-adjust:100%;text-size-adjust:100%}
  body{
    background:var(--paper);color:var(--ink);font-family:var(--sans);
    line-height:1.65;-webkit-font-smoothing:antialiased;
    padding:clamp(16px,4vw,48px);
  }
  main{max-width:46rem;margin:0 auto}
  .back{
    display:inline-block;margin-bottom:28px;font-size:14px;
    color:var(--a);text-decoration:none;
  }
  .back:hover{text-decoration:underline}
  h1{font-size:clamp(22px,3.4vw,30px);font-weight:650;letter-spacing:-.01em;margin:0 0 24px}
  h2{
    font-size:clamp(18px,2.4vw,22px);font-weight:650;letter-spacing:-.01em;
    margin:52px 0 14px;padding-top:8px;
  }
  h3{font-size:16px;font-weight:650;color:var(--ink);margin:32px 0 10px}
  p{margin:0 0 14px}
  a{color:var(--a)}
  strong{font-weight:650}
  hr{border:0;border-top:1px solid var(--line);margin:40px 0}
  code{
    font-family:var(--mono);font-size:.9em;background:var(--card);
    border:1px solid var(--line);border-radius:4px;padding:1px 5px;
  }
  ul{padding-left:1.3em;margin:0 0 14px}
  li{margin-bottom:8px}
  em{color:inherit}
  /* Wide content scrolls inside its own box; the page body never does. */
  .katex-block{overflow-x:auto;overflow-y:hidden;margin:20px 0;padding:2px 0;text-align:center}
  table{display:block;overflow-x:auto;border-collapse:collapse;font-size:14px;margin:0 0 18px}
  th,td{border-bottom:1px solid var(--line);padding:8px 14px 8px 0;text-align:left;vertical-align:top}
  th{font-weight:650;color:var(--slate);font-size:12px;letter-spacing:.02em;text-transform:uppercase}
  math{font-size:1.05em}
  .foot{margin-top:56px;padding-top:18px;border-top:1px solid var(--line);color:var(--slate);font-size:13px}
</style>
</head>
<body>
<main>
<a class="back" href="MortgageOfferAnalyzer.html">&larr; Mortgage Offer Analyzer</a>
${body}<p class="foot">Generated from <code>MATH.md</code> in the
<a href="https://github.com/phantom-signals/MortgageOfferAnalyzer">project repository</a>.
Nothing on this page is legal or financial advice.</p>
</main>
</body>
</html>
`;

fs.writeFileSync(OUT, page);
const equations = (page.match(/<math/g) || []).length;
const failures = (page.match(/katex-error/g) || []).length;
if (failures) throw new Error(`${failures} equation(s) failed to parse — see math.html`);
console.log(`math.html written — ${equations} equations, ${(page.length / 1024).toFixed(0)} KB`);
